---

- name: Create app dirrectory
  file:
    path: "{{ app_base_dir }}"
    state: directory
    mode: '0755'

- name: Create config dirrectory
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ html_config_dir }}"
  - "{{ filebeat_config_dir }}"

- name: Copy Docker Compose file
  template: 
    src: "{{ local_compose_file }}"
    dest: "{{ app_base_dir }}/docker-compose.yml"
    mode: '0664'

- name: Copy application files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0664'
  loop:
  - { src: "{{ local_html_config }}", dest: "{{ html_config_dir }}/index.html" }
  - { src: "{{ local_filebeat_file }}", dest: "{{ filebeat_config_dir }}/filebeat.yml"}

- name: Start ELK services
  command: docker-compose up -d
  args:
    chdir: "{{ app_base_dir }}"